config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :evaluations
  resources :evaluation_models
  resources :evaluation_factors
  resources :answer_options
  resources :questions

  get '/results' => 'results#index', :as => 'results'
  get '/results/:id' => 'results#show', :as => 'show_results'

  get '/tutorial' => 'tutorial#tutorial', :as => 'tutorial'

  get '/avaliar/:id/' => 'evaluations#responder', :as => 'responder'
  get '/avaliar' => 'evaluations#evaluation', :as => 'avaliar'
  get "info" => "infos#index", :as => 'info'
  get "/pessoas_EJ" => "infos#create"
  get '/home' => 'static_pages#home'

  post '/select_evaluation_factors' => 'evaluation_factors#select'

  post '/request_histories/aprovar_requisicao/:id' =>
       'request_histories#aprovar_requisicao', as: :aprovar_requisicao

  patch '/avaliar/:id' => 'evaluations#salvar'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :request_histories
  resources :junior_enterprises
  resources :profiles
  resources :roles
  resources :users, except: [:new, :create]

  devise_scope :user do
    root to: "devise/sessions#new"
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

end

app/models/request_history.rb
class RequestHistory < ActiveRecord::Base
  belongs_to :profile
  belongs_to :junior_enterprise
  belongs_to :role
  belongs_to :area

  validates_presence_of :email, :name, :junior_enterprise_id, :role_id, :area_id
end

app/controllers/request_histories_controller.rb
class RequestHistoriesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_request_history, only: [:show, :edit, :update, :destroy,
                                             :aprovar_requisicao]

  # GET /request_histories
  # GET /request_histories.json
  def index
    @request_histories = RequestHistory.all
  end

  # GET /request_histories/1
  # GET /request_histories/1.json
  def show
  end

  # GET /request_histories/new
  def new
    @request_history = RequestHistory.new
  end

  # GET /request_histories/1/edit
  def edit
  end

  # POST /request_histories
  # POST /request_histories.json
  def create
    @request_history = RequestHistory.new(request_history_params)

    respond_to do |format|
      if @request_history.save
        format.html { redirect_to @request_history, notice: 'Requisição enviada ao administrador.' }
        format.json { render :show, status: :created, location: @request_history }
      else
        format.html { render :new }
        format.json { render json: @request_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_histories/1
  # PATCH/PUT /request_histories/1.json
  def update
    respond_to do |format|
      if @request_history.update(request_history_params)
        format.html { redirect_to @request_history, notice: 'Requisição atualizada.' }
        format.json { render :show, status: :ok, location: @request_history }
      else
        format.html { render :edit }
        format.json { render json: @request_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_histories/1
  # DELETE /request_histories/1.json
  def destroy
    @request_history.destroy
    respond_to do |format|
      format.html { redirect_to request_histories_url, notice: 'Requisição cancelada.' }
      format.json { head :no_content }
    end
  end

  # POST /request_histories/1/aprovar_requisicao
  def aprovar_requisicao

    respond_to do |format|

        random_password = Devise.friendly_token.first 8
        @user = User.create(name: @request_history.name,
                            email: @request_history.email,
                            role_id: @request_history.role_id,
                            junior_enterprise_id: @request_history.junior_enterprise_id,
                            area_id: @request_history.area_id,
                               password: random_password)

        usuario_comum = Profile.find_by(name: 'Usuário Comum').id
        @user.update_attribute(:profile_id, usuario_comum)

        @request_history.update_attribute(:approved, true)

        UserMailer.user_registered(@user, random_password).deliver_now!
        format.html { redirect_to request_histories_path, notice: 'O cadastro foi aprovado com sucesso!' }

      else
        format.html { redirect_to request_histories_path, notice: 'Algo deu errado :c' }
      end

    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_history
      @request_history = RequestHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_history_params
      params.require(:request_history).permit(:name, :email, :profile_id, :junior_enterprise_id, :role_id, :approved, :area_id)
    end
end

app/helpers/request_histories_helper.rb
module RequestHistoriesHelper
end

app/views/request_histories/_form.html.slim
= form_for @request_history do |f|

  - if @request_history.errors.any?
    #error_explanation
      h2 = "#{pluralize(@request_history.errors.count, "error")} prohibited this request_history from being saved:"
      ul
        - @request_history.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class:'form-control'

  .form-group
    = f.label :email
    = f.text_field :email, class:'form-control'
  
  .form-group
    = f.label :junior_enterprise
    = f.select :junior_enterprise_id, 
               JuniorEnterprise.all.map { |je| [je.name, je.id] }, 
               {}, { class: 'form-control' }  

  .form-group
    = f.label :role
    = f.select :role_id,
               Role.all.map { |r| [r.name, r.id] }, 
               {}, { class: 'form-control' }  
  
  .form-group
    = f.label :area
    = f.select :area_id,
               Area.all.map { |a| [a.name, a.id] },
               {}, { class: 'form-control' }

  .actions = f.submit 'Pronto', class:'btn btn-info'

app/views/request_histories/edit.html.slim
h1 Atualizar Requisição

== render 'form'

= link_to 'Show', @request_history
'|
= link_to 'Back', request_histories_path

app/views/request_histories/index.html.slim
h1 Histórias de Requisição

table.table
  thead
    tr
      th Nome
      th Email
      th EJ
      th Cargo
      th Área
      th Aprovado?
      th 
      th
      th

  tbody
    - @request_histories.each do |request_history|
      tr
        td = request_history.name
        td = request_history.email
        td = request_history.try(:junior_enterprise).try(:name)
        td = request_history.try(:role).try(:name)
        td = request_history.try(:area).try(:name)
        td 
          - if request_history.approved
            | Sim
          - else
            | Não
        td = link_to 'Aprovar', aprovar_requisicao_path(request_history), method: :aprovar_requisicao
        td = link_to 'Show', request_history
        td = link_to 'Editar', edit_request_history_path(request_history)
        td = link_to 'Deletar', request_history, data: {:confirm => 'Tem certeza que deseja deletar?'}, :method => :delete

br

= link_to 'Nova História de Requisição', new_request_history_path

app/views/request_histories/new.html.slim
h1 Nova História de Requisição

== render 'form'

= link_to 'Voltar', request_histories_path

app/views/request_histories/show.html.slim
p
  strong Nome:
  = @request_history.name
p
  strong Email:
  = @request_history.email
p
  strong Aprovado:
  = @request_history.approved

= link_to 'Editar', edit_request_history_path(@request_history)
'|
= link_to 'Voltar', request_histories_path