config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :evaluations
  resources :evaluation_models
  resources :evaluation_factors
  resources :answer_options
  resources :questions

  get '/results' => 'results#index', :as => 'results'
  get '/results/:id' => 'results#show', :as => 'show_results'

  get '/tutorial' => 'tutorial#tutorial', :as => 'tutorial'

  get '/avaliar/:id/' => 'evaluations#responder', :as => 'responder'
  get '/avaliar' => 'evaluations#evaluation', :as => 'avaliar'
  get "info" => "infos#index", :as => 'info'
  get "/pessoas_EJ" => "infos#create"
  get '/home' => 'static_pages#home'

  post '/select_evaluation_factors' => 'evaluation_factors#select'

  post '/request_histories/aprovar_requisicao/:id' =>
       'request_histories#aprovar_requisicao', as: :aprovar_requisicao

  patch '/avaliar/:id' => 'evaluations#salvar'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :request_histories
  resources :junior_enterprises
  resources :profiles
  resources :roles
  resources :users, except: [:new, :create]

  devise_scope :user do
    root to: "devise/sessions#new"
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

end

app/models/evaluation_model.rb
class EvaluationModel < ActiveRecord::Base

  has_many :evaluation_factors_models, dependent: :destroy
  has_and_belongs_to_many :evaluation_factors

  belongs_to :role
  has_many :areas

  accepts_nested_attributes_for :evaluation_factors_models, reject_if: :all_blank, allow_destroy: true
  
end

app/controllers/evaluation_models_controller.rb
class EvaluationModelsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_evaluation_model, only: [:show, :edit, :update, :destroy]

  # GET /evaluation_models
  # GET /evaluation_models.json
  def index
    @evaluation_models = EvaluationModel.all
  end

  # GET /evaluation_models/1
  # GET /evaluation_models/1.json
  def show
  end

  # GET /evaluation_models/new
  def new
    @evaluation_model = EvaluationModel.new
  end

  # GET /evaluation_models/1/edit
  def edit
  end

  # POST /evaluation_models
  # POST /evaluation_models.json
  def create
    @evaluation_model = EvaluationModel.new(evaluation_model_params)

    respond_to do |format|
      if @evaluation_model.save
        format.html { redirect_to @evaluation_model, notice: 'Modelo de avaliação criado.' }
        format.json { render :show, status: :created, location: @evaluation_model }
      else
        format.html { render :new }
        format.json { render json: @evaluation_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluation_models/1
  # PATCH/PUT /evaluation_models/1.json
  def update
    respond_to do |format|
      if @evaluation_model.update(evaluation_model_params)
        format.html { redirect_to @evaluation_model, notice: 'Modelo de avaliação atualizado.' }
        format.json { render :show, status: :ok, location: @evaluation_model }
      else
        format.html { render :edit }
        format.json { render json: @evaluation_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluation_models/1
  # DELETE /evaluation_models/1.json
  def destroy
    @evaluation_model.destroy
    respond_to do |format|
      format.html { redirect_to evaluation_models_url, notice: 'Modelo de avaliação deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation_model
      @evaluation_model = EvaluationModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_model_params
      params.require(:evaluation_model).permit(
        :name,
        :role_id,
        :area_id,
        evaluation_factors_models_attributes: [:id, :evaluation_factor_id, :_destroy, evaluation_factor_attributes: [:id, :name, :_destroy]]
      )
    end
end

app/helpers/evaluation_models_helper.rb
module EvaluationModelsHelper
end

app/views/evaluation_models/_evaluation_factor_fields.html.slim
.nested-fields
  
  .form-group
    = f.label 'Nome'
    = f.text_field :name, class: 'form-control'

app/views/evaluation_models/_evaluation_factors_model_fields.html.slim
.nested-fields.evaluation-factors-model-fields

  #evaluation_factor_from_list
    .form-group
      = f.select :evaluation_factor_id,
                 EvaluationFactor.all.map { |ef| [ef.name, ef.id] },
                 { include_blank: 'Selecione o fator de avaliação' },
                 { class: 'form-control' }

  = link_to_add_association 'Ou crie um novo fator de avaliação', 
                            f, :evaluation_factor,
                            class: 'btn btn-primary',
                            style: 'margin-right: 5px'

  = link_to_remove_association "Remover", 
                               f, class: 'btn btn-danger'

  hr.divider

app/views/evaluation_models/_form.html.slim
= form_for @evaluation_model do |f|

  - if @evaluation_model.errors.any?

    #error_explanation
      h2 = "#{pluralize(@evaluation_model.errors.count, "error")} prohibited this evaluation_model from being saved:"
      ul
        - @evaluation_model.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label 'Nome'
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label 'Cargo'
    = f.select :role_id, Role.all.map { |r| [r.name, r.id] }, 
      { include_blank: 'Selecione o cargo' }, 
      { class: 'form-control' }

  .form-group
    = f.label 'Área'
    = f.select :area_id, Area.all.map { |a| [a.name, a.id] }, 
      { include_blank: 'Selecione a área' }, 
      { class: 'form-control' }
  
  h3 Fatores de Avaliação

  br

  #evaluation_factors
    = f.fields_for :evaluation_factors_models do |evaluation_factor_model|
      = render 'evaluation_factors_model_fields', f: evaluation_factor_model
    = link_to_add_association 'Adicionar um novo fator de avaliação', 
      f, :evaluation_factors_models, class: 'btn btn-info'

  br

  .actions
    = f.submit 'Salvar', class: 'btn btn-info'

javascript:
  $(document).ready(function() {
    $("#evaluation_factors a.add_fields").
      data("association-insertion-position", 'before').
      data("association-insertion-node", 'this');

    $('#evaluation_factors').on('cocoon:after-insert',
         function() {
             $(".evaluation-factors-model-fields a.add_fields").
                 data("association-insertion-position", 'before').
                 data("association-insertion-node", 'this');
             $('.evaluation-factors-model-fields').on('cocoon:after-insert',
                  function() {
                    $(this).children("#evaluation_factor_from_list").remove();
                    $(this).children("a.add_fields").hide();
                  });
         });
  });

app/views/evaluation_models/edit.html.slim
h1 Atualizar Modelo de Avaliação

== render 'form'

= link_to 'Show', @evaluation_model
'|
= link_to 'Voltar', evaluation_models_path

app/views/evaluation_models/index.html.slim
h1 Modelos de Avaliação

table.table
  thead
    tr
      th Nome
      th
      th
      th

  tbody
    - @evaluation_models.each do |evaluation_model|
      tr
        td = evaluation_model.name
        td = link_to 'Show', evaluation_model
        td = link_to 'Editar', edit_evaluation_model_path(evaluation_model)
        td = link_to 'Deletar', evaluation_model, data: {:confirm => 'Tem certeza que deseja deletar?'}, :method => :delete

br

= link_to 'Novo Modelo de Avaliação', new_evaluation_model_path

app/views/evaluation_models/new.html.slim
h1 Novo Modelo de Avaliação

== render 'form'

= link_to 'Voltar', evaluation_models_path

app/views/evaluation_models/show.html.slim
p
  strong Nome:
  = @evaluation_model.name

= link_to 'Editar', edit_evaluation_model_path(@evaluation_model)
'|
= link_to 'Voltar', evaluation_models_path