config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :evaluations
  resources :evaluation_models
  resources :evaluation_factors
  resources :answer_options
  resources :questions

  get '/results' => 'results#index', :as => 'results'
  get '/results/:id' => 'results#show', :as => 'show_results'

  get '/tutorial' => 'tutorial#tutorial', :as => 'tutorial'

  get '/avaliar/:id/' => 'evaluations#responder', :as => 'responder'
  get '/avaliar' => 'evaluations#evaluation', :as => 'avaliar'
  get "info" => "infos#index", :as => 'info'
  get "/pessoas_EJ" => "infos#create"
  get '/home' => 'static_pages#home'

  post '/select_evaluation_factors' => 'evaluation_factors#select'

  post '/request_histories/aprovar_requisicao/:id' =>
       'request_histories#aprovar_requisicao', as: :aprovar_requisicao

  patch '/avaliar/:id' => 'evaluations#salvar'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :request_histories
  resources :junior_enterprises
  resources :profiles
  resources :roles
  resources :users, except: [:new, :create]

  devise_scope :user do
    root to: "devise/sessions#new"
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end

end

app/models/answer_option.rb
class AnswerOption < ActiveRecord::Base
  has_and_belongs_to_many :questions
  has_many :answers
end

app/controllers/answer_options_controller.rb
class AnswerOptionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_answer_option, only: [:show, :edit, :update, :destroy]

  # GET /answer_options
  # GET /answer_options.json
  def index
    @answer_options = AnswerOption.all
  end

  # GET /answer_options/1
  # GET /answer_options/1.json
  def show
  end

  # GET /answer_options/new
  def new
    @answer_option = AnswerOption.new
  end

  # GET /answer_options/1/edit
  def edit
  end

  # POST /answer_options
  # POST /answer_options.json
  def create
    @answer_option = AnswerOption.new(answer_option_params)

    respond_to do |format|
      if @answer_option.save
        format.html { redirect_to @answer_option, notice: 'Opção de resposta criada.' }
        format.json { render :show, status: :created, location: @answer_option }
      else
        format.html { render :new }
        format.json { render json: @answer_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_options/1
  # PATCH/PUT /answer_options/1.json
  def update
    respond_to do |format|
      if @answer_option.update(answer_option_params)
        format.html { redirect_to @answer_option, notice: 'Opção de resposta atualizada.' }
        format.json { render :show, status: :ok, location: @answer_option }
      else
        format.html { render :edit }
        format.json { render json: @answer_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_options/1
  # DELETE /answer_options/1.json
  def destroy
    @answer_option.destroy
    respond_to do |format|
      format.html { redirect_to answer_options_url, notice: 'Opção de resposta deletada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_option
      @answer_option = AnswerOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_option_params
      params.require(:answer_option).permit(:option, :description, :question_id)
    end
end

app/helpers/answer_options_helper.rb
module AnswerOptionsHelper
end

app/views/answer_options/_form.html.slim
= form_for @answer_option do |f|
  - if @answer_option.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer_option.errors.count, "error")} prohibited this answer_option from being saved:"
      ul
        - @answer_option.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :option
    = f.text_field :option,{ class:'form-control' }
  .field
    = f.label :description
    = f.text_field :description,{ class:'form-control' }
  .actions 
    = f.submit 'Salvar', class: 'btn btn-info'

app/views/answer_options/edit.html.slim
h1 Atualizar Opções de Resposta

== render 'form'

= link_to 'Show', @answer_option
'|
= link_to 'Voltar', answer_options_path

app/views/answer_options/index.html.slim
h1 Opções de Resposta

table.table
  thead
    tr
      th Opção
      th Descrição
      th
      th
      th

  tbody
    - @answer_options.each do |answer_option|
      tr
        td = answer_option.option
        td = answer_option.description
        td = link_to 'Show', answer_option
        td = link_to 'Editar', edit_answer_option_path(answer_option)
        td = link_to 'Deletar', answer_option, data: {:confirm => 'Tem certeza que deseja deletar?'}, :method => :delete

br

= link_to 'Nova Opção de Resposta', new_answer_option_path

app/views/answer_options/new.html.slim
h1 Nova Opção de Resposta

== render 'form'

= link_to 'Voltar', answer_options_path

app/views/answer_options/show.html.slim
p
  strong Opção:
  = @answer_option.option
p
  strong Descrição:
  = @answer_option.description

= link_to 'Editar', edit_answer_option_path(@answer_option)
'|
= link_to 'Voltar', answer_options_path